### PR TITLE
Delete bad code

### PR DESCRIPTION
**Pull request by Voxed**
Delete all of the poorly written code in the repository to make room for improvements

### CODE REVIEW

**Comment by lukas-gartman** [comment]
i agree there is much needed room for improvements

**Comment by Voxed** [comment]
@sebastianselander

**Comment by sebastianselander** [comment]
The critique is fair and the issue should absolutely be taken care of.

**Comment by Voxed** [comment]
The owner of this repository has now connected me through private channels in an attempt to bully me away from contributing to this repository. This is despicable @samhamnam

**Comment by loafey** [comment]
I will eat your spoons

**Pull request closed without merging**
